### ISSUE TITLE
Github Markdown highlighting: Syntax Highlighted fenced code blocks breaks highlighting 

### ISSUE THREAD

**Issue by armadillu** [atom/base16-tomorrow-dark-theme#43] opened 2017-08-09 21:26 UTC
### Description

For Markdown files  : Syntax highlighted fenced code blocks break markdown syntax highlighting.

By ```Syntax highlighted fenced code blocks``` I refer to a code block in which the source code language is specified, as described [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/). I am unclear on how standard this feature is, but it would be a nice to support it if possible.

### Steps to Reproduce
![](https://farm5.staticflickr.com/4403/35660960643_957433c151_z_d.jpg)

As you can see in the picture, the "c++" label after the fenced code block sequence (\```) breaks the highlighting. The fenced code block section should be yellow; and the yellow should stop once the section is closed. Instead, the (\```c++) line is not recognised as a code block starter, and the ending (\```) is.

**Comment by simurai** [comment] 2018-08-24 04:32
This looks like it's a duplicate of https://github.com/atom/language-gfm/issues/21.

As a workaround, seems that [language-markdown](https://atom.io/packages/language-markdown) doesn't have the problem.

**Closed by simurai** 2018-08-24 04:32 UTC
