### ISSUE TITLE
Ruby Syntax Highlighting Error

### ISSUE THREAD

**Issue by wazoo** [atom/base16-tomorrow-dark-theme#12] opened 2015-02-04 19:23 UTC
I have a long line (550 characters) and at about character 450 the comment syntax grammar for strings seems to be broken.  This is a string surrounded by " with ' inside it using embedded ruby ( #{variable}), seems to work fine until the line gets too long.  It is strange, it doesn't break all of the syntax in the rest of the file but anything that doesn't have another style (like a library or a variable) is just green.  

I checked it with another theme (solarized) and it worked fine there so that is why I am reporting this here and not on the atom project, if that is wrong let me know!

**Comment by benogle** [comment] 2015-02-04 19:27
Hey, this is a dupe of https://github.com/atom/atom/issues/1667

**Closed by benogle** 2015-02-04 19:27 UTC
